spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/5teams?serverTimezone=Asia/Seoul
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.Jellabo.Team_miniPj_Backend